
# services:
#  express-app: # Сервер Express
#     build: .
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db
#       - react-app
#     environment:
#       DATABASE_URL: 'mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true'
#  db: # База данных
#     image: prismagraphql/mongo-single-replica:5.0.3
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: monty
#       MONGO_INITDB_ROOT_PASSWORD: pass
#  react-app: # React-приложение
#     build: ../REACT-CLIENT # Путь к вашему React-приложению относительно корня вашего проекта
#     ports:
#       - '80:80' # Порт, на котором будет доступно ваше React-приложение
#       - '8000:8000' # Порт, на котором будет доступно ваше React-приложение
# volumes:
#  react_app: # Объявление именованного тома
version: '3.8'

services:
  express-app: # Сервер Express
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - react-app
    environment:
      DATABASE_URL: 'postgresql://postgres:VJCjsDzTaotFBquuhtufSGpaDVidSTKA@autorack.proxy.rlwy.net:14397/railway'

  db: # База данных PostgreSQL
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VJCjsDzTaotFBquuhtufSGpaDVidSTKA
      POSTGRES_DB: railway

  react-app: # React-приложение
    build: ../REACT-CLIENT # Путь к вашему React-приложению относительно корня вашего проекта
    ports:
      - '80:80' # Порт, на котором будет доступно ваше React-приложение
      - '8000:8000' # Порт, на котором будет доступно ваше React-приложение
